services:
  - type: web
    name: nails-salon-backend
    env: node
    plan: free
    rootDir: backend
    buildCommand: npm install && npx prisma generate && npm run build
    startCommand: npm run start
    envVars:
      - key: PORT
        value: 10000
      - key: DATABASE_URL
        sync: false
      - key: DIRECT_URL
        sync: false
